language: node_js
node_js:
    - "node"
script: npm test
before_script: npm install
after_script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --captureExceptions test/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage